### ISSUE TITLE
Follow Google Publisher Policies

### ISSUE THREAD

**Issue by clay53** [ClaytonDoesThings/ClaytonXYZ#36]
Despite this site being live for over 4+ years, I have made lots of negative money on it. I have decided that I will not be applying for Adsense, but this is a good checklist for bringing on other sponsors.

Tasks that need to be completed before applying based on [Google Publisher Polices](https://support.google.com/adsense/answer/10502938?hl=en&visit_id=637764042068400032-1675761043&rd=2):
- [x] No illegal content
- [x] No IP Abuse
- - [x] No DMCA violations
- - [x] No sale of counterfeit products
- [x] No dangerous or derogatory content
- - [x] No dumb discrimination
- - [x] No harassment/bullying of individuals/groups
- - [x] No threats of physical/mental harm
- - [x] No extortion
- [x] No animal cruelty
- [ ] No misrepresentative content
- - [ ] No misrepresentation/concealment of the author, publisher, purpose, or content
- - - [ ] #29 
- - [x] No false endorsement/affiliation
- [x] No unreliable/harmful claims
- - [x] No demonstrably false claims significantly undermining trust/participation in democratic/electoral process
- - [x] No promotion of harmful health claims/major health crisis contradicting scientific consensus
- - [x] No contradicting scientific consensus on climate change
- [x] No Deceptive practices
- - [x] No engagement baiting
- - [x] No phishing
- - [x] No misrepresenting/concealing identity when it's a social issue/public concern
- - [x] No political content/matters of public concern to foreign countries other than one's own while misrepresenting one's own country of origin or other relevant details
- [x] No manipulated media related to public concern
- [x] No enabling dishonest behavior
- - [x] No helping users mislead others
- - [x] No promotion of hacking/cracking
- - [x] No enabling/promoting a user to breach another's privacy w/o authorization (excluding parents->children & investigation services)
- [ ] No malicious or unwanted software
- - [x] No malware
- - - [ ] #33
- [x] No sexually explicit content
- - [x] No graphic/textual sexual content
- - [x] No underage or non-consensual sexual themes
- [x] No compensated sexual acts
- [x] No mail order brides
- [x] No Adult themes in family content
- [x] No CSAM
- [x] All information submitted to ad systems is honest
- [x] No ads interfering with content or user interactions
- - [x] No placement of ads too close to clickable items
- - [x] Ads do not severely interfere with content by things like overlaying content or pushing content off-display
- - [x] No ads on their own page or forcing interaction with ads to continue
- [x] Ads are only on publisher content excluding low-value content like notification pages
- [x] Ads are not out of the context they're targeting
- [x] There's more publisher content than ad
- [x] Content is in a [supported language](https://support.google.com/publisherpolicies/answer/10436912)
- [ ] Privacy disclosures
- - - [ ] #34
- [x] No interfering with Google-related cookies (and general rule - no one else's)
- [ ] Identifying users
- - [x] No use of device identifiers other than those that are user-resettable for advertising use (no user identifiers other than future cookie for account session
- - [x] No sending Google (or anyone) personal information or permanent identifiers of a device
- - [x] No using Google services to merge non-personally identifiable info with info that is personally identifiable
- - [ ] Compliance with the EU user consent policy (cookies related to things like sign-in info are exempt)
- - - [ ] #35
- [x] Use of device and location data
- - [x] Disclosures for purposes for which data may be used (including sharing with partners)
- - [x] Obtain express consent before collecting information
- - [x] Data sent to Google must be encrypted or sent in an encrypted channel with disclosure (none)
- [x] Standard Contractual Clauses
- - [x] Partners use personal data consistent with consent provided in the first place
- - [x] Partners must protect personal data at least equivalent to what's required under SCC
- [x] Compliance with COPPA
- - [x] Properly tag content for those <13yr (none)
- - [x] No interest-based advertising for those <13yr (none)
- [x] No ads on pages that don't follow the [Webmaster Quality Guidelines](https://developers.google.com/search/docs/advanced/guidelines/webmaster-guidelines)
- [x] No pages with [Abusive Experiences](https://support.google.com/webtools/answer/7347327)
- [x] Follow the [Better Ads Standard](https://www.betterads.org/standards/)
- [x] No ads on domains where we're not authorized sellers of the [inventory in ads.txt](https://support.google.com/publisherpolicies/answer/11128498)
- [x] Compliance with sanctions
